//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notarius.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notarius.DataAccess.SQLResources", typeof(SQLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Patient (MRN varchar(100), Firstname varchar(50), Lastname varchar(50), Address varchar(100),  City varchar(30), State varchar(30), Zip varchar(20)).
        /// </summary>
        internal static string CreatePatientTable {
            get {
                return ResourceManager.GetString("CreatePatientTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Schedule(Key int identity,  MRN varchar(100), ProviderId varchar(100), ScheduleTime varchar(100)).
        /// </summary>
        internal static string CreateScheduleTable {
            get {
                return ResourceManager.GetString("CreateScheduleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Patient where MRN=@MRN.
        /// </summary>
        internal static string DeletePatient {
            get {
                return ResourceManager.GetString("DeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Schedule WHERE KEY=@KEY.
        /// </summary>
        internal static string DeleteSchedule {
            get {
                return ResourceManager.GetString("DeleteSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT mrn, firstname,lastname,address,city,state,zip FROM Patient.
        /// </summary>
        internal static string GetAllPatients {
            get {
                return ResourceManager.GetString("GetAllPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Key, MRN, ProviderId, ScheduleTime FROM Schedule.
        /// </summary>
        internal static string GetAllSchedules {
            get {
                return ResourceManager.GetString("GetAllSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(Key) FROM Schedule.
        /// </summary>
        internal static string GetNextSheduleSEQ {
            get {
                return ResourceManager.GetString("GetNextSheduleSEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MRN,  firstname,lastname,address,city,state,zip FROM Patient where MRN = @MRN.
        /// </summary>
        internal static string GetPatient {
            get {
                return ResourceManager.GetString("GetPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MRN, PROVIDERID, SCHEDULETIME FROM SCHEDULE WHERE KEY=@KEY.
        /// </summary>
        internal static string GetSchedule {
            get {
                return ResourceManager.GetString("GetSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Patient(mrn,firstname, lastname, address,city,state,zip)VALUES(@MRN,@Firstname,@LastName,@Address,@City,@State,@Zip).
        /// </summary>
        internal static string InsertPatient {
            get {
                return ResourceManager.GetString("InsertPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Schedule(key,mrn,providerid,scheduletime)values(@key, @mrn, @providerId, @scheduletime).
        /// </summary>
        internal static string InsertSchedule {
            get {
                return ResourceManager.GetString("InsertSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Patient SET Firstname=@FirstName, LastName=@LastName, Address=@Address, City=@City, State=@State, Zip=@Zip WHERE MRN = @Mrn.
        /// </summary>
        internal static string UpdatePatient {
            get {
                return ResourceManager.GetString("UpdatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SCHEDULE SET MRN=@MRN, ProviderId=@ProviderId, ScheduleTime=@Scheduletime WHERE KEY=@KEY.
        /// </summary>
        internal static string UpdateSchedule {
            get {
                return ResourceManager.GetString("UpdateSchedule", resourceCulture);
            }
        }
    }
}
